version: 2

sources:
  - name: RAW
    database: NETFLIX 
    schema: RAW
    tables:
      - name: raw_genome_scores
      - name: raw_genome_tags
      - name: raw_movies
      - name: raw_tags
      - name: raw_links
      - name: raw_ratings
